### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by TylerBarnes** [iPriceGroup/critical-css#2]
Is it possible to use this with straight php and no laravel?

**Comment by antonbormotov** [comment]
I don't think so, since it relies on Laravel's classes such as Request, HttpKernel and cli generator. Anyway, it is a wrapper around npm package: You can see how it builds command to generate critical css here `src/CssGenerators/CriticalGenerator.php`, how does it fetch actual html and build something similar. I assume, it is possible to find some examples on Stackoverflow or elsewhere.

**Comment by TylerBarnes** [comment]
Awesome, that makes sense. Thanks for the tips!
